site_name: versionator
site_description: Project focuses on managing firmware versioning.
repo_url: https://github.com/davidlso/versionator
site_dir: site
copyright: Copyright &copy; 2020, <a href="https://github.com/davidlso">davidlso</a>.
dev_addr: 0.0.0.0:8001

nav:
  - Home: 'index.md'
  - API:
    - Authentication: 'api/authentication.md'
    - Users: 'api/users.md'
