# Generated by Django 3.1.6 on 2021-02-06 02:00

from django.db import migrations, models
import uuid
import versionator.firmware.models
import versionator.firmware.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Firmmware',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('project_name', models.CharField(max_length=255)),
                ('version', models.CharField(max_length=12, validators=[versionator.firmware.validators.validate_version_format, versionator.firmware.validators.validate_version_only_number])),
                ('compatible_card_name', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to=versionator.firmware.models.file_rename, validators=[versionator.firmware.validators.validate_file_extension])),
            ],
        ),
    ]
