# Generated by Django 3.1.6 on 2021-02-09 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firmware', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Firmmware',
            new_name='Firmware',
        ),
    ]
